config/routes.rb
Rails.application.routes.draw do

  resources :crumb_templates
  resources :campaign_target_pages
  resources :campaign_templates
	root to: 'campaigns#index'
  resources :campaign_colors
  resources :campaign_tasks
  resources :tasks
  resources :target_pages
  resources :templates
  resources :campaigns
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/campaign_color.rb
class CampaignColor < ApplicationRecord
  belongs_to :campaign

end

app/controllers/campaign_colors_controller.rb
class CampaignColorsController < ApplicationController
  before_action :set_campaign_color, only: [:show, :edit, :update, :destroy]

  # GET /campaign_colors
  # GET /campaign_colors.json
  def index
    @campaign_colors = CampaignColor.all
  end

  # GET /campaign_colors/1
  # GET /campaign_colors/1.json
  def show
  end

  # GET /campaign_colors/new
  def new
    @campaign_color = CampaignColor.new
  end

  # GET /campaign_colors/1/edit
  def edit
  end

  # POST /campaign_colors
  # POST /campaign_colors.json
  def create
    @campaign_color = CampaignColor.new(campaign_color_params)

    respond_to do |format|
      if @campaign_color.save
        format.html { redirect_to @campaign_color, notice: 'Campaign color was successfully created.' }
        format.json { render :show, status: :created, location: @campaign_color }
      else
        format.html { render :new }
        format.json { render json: @campaign_color.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaign_colors/1
  # PATCH/PUT /campaign_colors/1.json
  def update
    respond_to do |format|
      if @campaign_color.update(campaign_color_params)
        format.html { redirect_to @campaign_color, notice: 'Campaign color was successfully updated.' }
        format.json { render :show, status: :ok, location: @campaign_color }
      else
        format.html { render :edit }
        format.json { render json: @campaign_color.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaign_colors/1
  # DELETE /campaign_colors/1.json
  def destroy
    @campaign_color.destroy
    respond_to do |format|
      format.html { redirect_to campaign_colors_url, notice: 'Campaign color was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign_color
      @campaign_color = CampaignColor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campaign_color_params
      params.require(:campaign_color).permit(:campaign_id, :hex_value, :color_type)
    end
end

app/helpers/campaign_colors_helper.rb
module CampaignColorsHelper
end

app/views/campaign_colors/_form.html.erb
<%= form_with(model: campaign_color, local: true) do |form| %>
  <% if campaign_color.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(campaign_color.errors.count, "error") %> prohibited this campaign_color from being saved:</h2>

      <ul>
      <% campaign_color.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :campaign_id %>
    <%= form.text_field :campaign_id, id: :campaign_color_campaign_id %>
  </div>

  <div class="field">
    <%= form.label :hex_value %>
    <%= form.text_field :hex_value, id: :campaign_color_hex_value %>
  </div>

  <div class="field">
    <%= form.label :color_type %>
    <%= form.text_field :color_type, id: :campaign_color_color_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/campaign_colors/edit.html.erb
<h1>Editing Campaign Color</h1>

<%= render 'form', campaign_color: @campaign_color %>

<%= link_to 'Show', @campaign_color %> |
<%= link_to 'Back', campaign_colors_path %>

app/views/campaign_colors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Campaign Colors</h1>

<table>
  <thead>
    <tr>
      <th>Campaign</th>
      <th>Hex value</th>
      <th>Color type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @campaign_colors.each do |campaign_color| %>
      <tr>
        <td><%= campaign_color.campaign %></td>
        <td><%= campaign_color.hex_value %></td>
        <td><%= campaign_color.color_type %></td>
        <td><%= link_to 'Show', campaign_color %></td>
        <td><%= link_to 'Edit', edit_campaign_color_path(campaign_color) %></td>
        <td><%= link_to 'Destroy', campaign_color, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Campaign Color', new_campaign_color_path %>

app/views/campaign_colors/new.html.erb
<h1>New Campaign Color</h1>

<%= render 'form', campaign_color: @campaign_color %>

<%= link_to 'Back', campaign_colors_path %>

app/views/campaign_colors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Campaign:</strong>
  <%= @campaign_color.campaign %>
</p>

<p>
  <strong>Hex value:</strong>
  <%= @campaign_color.hex_value %>
</p>

<p>
  <strong>Color type:</strong>
  <%= @campaign_color.color_type %>
</p>

<%= link_to 'Edit', edit_campaign_color_path(@campaign_color) %> |
<%= link_to 'Back', campaign_colors_path %>