config/routes.rb
Rails.application.routes.draw do

  resources :crumb_templates
  resources :campaign_target_pages
  resources :campaign_templates
	root to: 'campaigns#index'
  resources :campaign_colors
  resources :campaign_tasks
  resources :tasks
  resources :target_pages
  resources :templates
  resources :campaigns
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/target_page.rb
class TargetPage < ApplicationRecord
  has_many :campaign_target_pages
end

app/controllers/target_pages_controller.rb
class TargetPagesController < ApplicationController
  before_action :set_target_page, only: [:show, :edit, :update, :destroy]

  # GET /target_pages
  # GET /target_pages.json
  def index
    @target_pages = TargetPage.all
  end

  # GET /target_pages/1
  # GET /target_pages/1.json
  def show
  end

  # GET /target_pages/new
  def new
    @target_page = TargetPage.new
  end

  # GET /target_pages/1/edit
  def edit
  end

  # POST /target_pages
  # POST /target_pages.json
  def create
    @target_page = TargetPage.new(target_page_params)

    respond_to do |format|
      if @target_page.save
        format.html { redirect_to @target_page, notice: 'Target page was successfully created.' }
        format.json { render :show, status: :created, location: @target_page }
      else
        format.html { render :new }
        format.json { render json: @target_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /target_pages/1
  # PATCH/PUT /target_pages/1.json
  def update
    respond_to do |format|
      if @target_page.update(target_page_params)
        format.html { redirect_to @target_page, notice: 'Target page was successfully updated.' }
        format.json { render :show, status: :ok, location: @target_page }
      else
        format.html { render :edit }
        format.json { render json: @target_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /target_pages/1
  # DELETE /target_pages/1.json
  def destroy
    @target_page.destroy
    respond_to do |format|
      format.html { redirect_to target_pages_url, notice: 'Target page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_target_page
      @target_page = TargetPage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def target_page_params
      params.require(:target_page).permit(:campaign_id, :target_page_name)
    end
end

app/helpers/target_pages_helper.rb
module TargetPagesHelper
end

app/views/target_pages/_form.html.erb
<%= form_with(model: target_page, local: true) do |form| %>
  <% if target_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(target_page.errors.count, "error") %> prohibited this target_page from being saved:</h2>

      <ul>
      <% target_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :target_page_name %>
    <%= form.text_field :target_page_name, id: :target_page_target_page_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/target_pages/edit.html.erb
<h1>Editing Target Page</h1>

<%= render 'form', target_page: @target_page %>

<%= link_to 'Show', @target_page %> |
<%= link_to 'Back', target_pages_path %>

app/views/target_pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Target Pages</h1>

<table>
  <thead>
    <tr>
      <th>Target page name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @target_pages.each do |target_page| %>
      <tr>
        <td><%= target_page.target_page_name %></td>
        <td><%= link_to 'Show', target_page %></td>
        <td><%= link_to 'Edit', edit_target_page_path(target_page) %></td>
        <td><%= link_to 'Destroy', target_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Target Page', new_target_page_path %>

app/views/target_pages/new.html.erb
<h1>New Target Page</h1>

<%= render 'form', target_page: @target_page %>

<%= link_to 'Back', target_pages_path %>

app/views/target_pages/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Target page name:</strong>
  <%= @target_page.target_page_name %>
</p>

<%= link_to 'Edit', edit_target_page_path(@target_page) %> |
<%= link_to 'Back', target_pages_path %>