config/routes.rb
Rails.application.routes.draw do

  resources :crumb_templates
  resources :campaign_target_pages
  resources :campaign_templates
	root to: 'campaigns#index'
  resources :campaign_colors
  resources :campaign_tasks
  resources :tasks
  resources :target_pages
  resources :templates
  resources :campaigns
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/campaign_task.rb
class CampaignTask < ApplicationRecord
  belongs_to :campaign
  belongs_to :task
end

app/controllers/campaign_tasks_controller.rb
class CampaignTasksController < ApplicationController
  before_action :set_campaign_task, only: [:show, :edit, :update, :destroy]

  # GET /campaign_tasks
  # GET /campaign_tasks.json
  def index
    @campaign_tasks = CampaignTask.all
  end

  # GET /campaign_tasks/1
  # GET /campaign_tasks/1.json
  def show
  end

  # GET /campaign_tasks/new
  def new
    @campaign_task = CampaignTask.new
  end

  # GET /campaign_tasks/1/edit
  def edit
  end

  # POST /campaign_tasks
  # POST /campaign_tasks.json
  def create
    @campaign_task = CampaignTask.new(campaign_task_params)

    respond_to do |format|
      if @campaign_task.save
        format.html { redirect_to @campaign_task, notice: 'Campaign task was successfully created.' }
        format.json { render :show, status: :created, location: @campaign_task }
      else
        format.html { render :new }
        format.json { render json: @campaign_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaign_tasks/1
  # PATCH/PUT /campaign_tasks/1.json
  def update
    respond_to do |format|
      if @campaign_task.update(campaign_task_params)
        format.html { redirect_to @campaign_task, notice: 'Campaign task was successfully updated.' }
        format.json { render :show, status: :ok, location: @campaign_task }
      else
        format.html { render :edit }
        format.json { render json: @campaign_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaign_tasks/1
  # DELETE /campaign_tasks/1.json
  def destroy
    @campaign_task.destroy
    respond_to do |format|
      format.html { redirect_to campaign_tasks_url, notice: 'Campaign task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign_task
      @campaign_task = CampaignTask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campaign_task_params
      params.require(:campaign_task).permit(:campaign_id, :task_id, :incentive_type, :amount)
    end
end

app/helpers/campaign_tasks_helper.rb
module CampaignTasksHelper
end

app/views/campaign_tasks/_form.html.erb
<%= form_with(model: campaign_task, local: true) do |form| %>
  <% if campaign_task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(campaign_task.errors.count, "error") %> prohibited this campaign_task from being saved:</h2>

      <ul>
      <% campaign_task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :campaign_id %>
    <%= form.text_field :campaign_id, id: :campaign_task_campaign_id %>
  </div>

  <div class="field">
    <%= form.label :task_id %>
    <%= form.text_field :task_id, id: :campaign_task_task_id %>
  </div>

  <div class="field">
    <%= form.label :incentive_type %>
    <%= form.text_field :incentive_type, id: :campaign_task_incentive_type %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount, id: :campaign_task_amount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/campaign_tasks/edit.html.erb
<h1>Editing Campaign Task</h1>

<%= render 'form', campaign_task: @campaign_task %>

<%= link_to 'Show', @campaign_task %> |
<%= link_to 'Back', campaign_tasks_path %>

app/views/campaign_tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Campaign Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Campaign</th>
      <th>Task</th>
      <th>Incentive type</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @campaign_tasks.each do |campaign_task| %>
      <tr>
        <td><%= campaign_task.campaign %></td>
        <td><%= campaign_task.task %></td>
        <td><%= campaign_task.incentive_type %></td>
        <td><%= campaign_task.amount %></td>
        <td><%= link_to 'Show', campaign_task %></td>
        <td><%= link_to 'Edit', edit_campaign_task_path(campaign_task) %></td>
        <td><%= link_to 'Destroy', campaign_task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Campaign Task', new_campaign_task_path %>

app/views/campaign_tasks/new.html.erb
<h1>New Campaign Task</h1>

<%= render 'form', campaign_task: @campaign_task %>

<%= link_to 'Back', campaign_tasks_path %>

app/views/campaign_tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Campaign:</strong>
  <%= @campaign_task.campaign %>
</p>

<p>
  <strong>Task:</strong>
  <%= @campaign_task.task %>
</p>

<p>
  <strong>Incentive type:</strong>
  <%= @campaign_task.incentive_type %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @campaign_task.amount %>
</p>

<%= link_to 'Edit', edit_campaign_task_path(@campaign_task) %> |
<%= link_to 'Back', campaign_tasks_path %>