config/routes.rb
Rails.application.routes.draw do

  resources :crumb_templates
  resources :campaign_target_pages
  resources :campaign_templates
	root to: 'campaigns#index'
  resources :campaign_colors
  resources :campaign_tasks
  resources :tasks
  resources :target_pages
  resources :templates
  resources :campaigns
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :user
  has_many :campaign_colors
  has_many :campaign_tasks
  has_many :campaign_templates
  has_many :campaign_target_pagees
end

app/models/campaign_color.rb
class CampaignColor < ApplicationRecord
  belongs_to :campaign

end

app/models/campaign_target_page.rb
class CampaignTargetPage < ApplicationRecord
  belongs_to :campaign
  belongs_to :target_page
end

app/models/campaign_task.rb
class CampaignTask < ApplicationRecord
  belongs_to :campaign
  belongs_to :task
end

app/models/campaign_template.rb
class CampaignTemplate < ApplicationRecord
  belongs_to :campaign
  belongs_to :template
end

app/models/crumb_template.rb
class CrumbTemplate < ApplicationRecord
end

app/models/target_page.rb
class TargetPage < ApplicationRecord
  has_many :campaign_target_pages
end

app/models/task.rb
class Task < ApplicationRecord
	has_many :campaign_tasks
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]

  # GET /campaigns
  # GET /campaigns.json
  def index
    @campaigns = Campaign.all
  end

  # GET /campaigns/1
  # GET /campaigns/1.json
  def show
  end

  # GET /campaigns/new
  def new
    @campaign = Campaign.new
  end

  # GET /campaigns/1/edit
  def edit
  end

  # POST /campaigns
  # POST /campaigns.json
  def create
    @campaign = Campaign.new(campaign_params)

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to @campaign, notice: 'Campaign was successfully created.' }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaigns/1
  # PATCH/PUT /campaigns/1.json
  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.html { redirect_to @campaign, notice: 'Campaign was successfully updated.' }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1
  # DELETE /campaigns/1.json
  def destroy
    @campaign.destroy
    respond_to do |format|
      format.html { redirect_to campaigns_url, notice: 'Campaign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campaign_params
      params.require(:campaign).permit(:user_id, :compaign_name, campaign_target_pages_attributes: [:id, :campaign_id, :target_page_id], campaign_tasks_attributes: [:id, :campaign_id, :task_id, :incentive_type, :amount], campaign_templates_attributes: [:id, :campaign_id, :template_id], campaign_colors_attributes: [:id, :campaign_id, :hex_value, :color_type])
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:store_name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaign_colors_helper.rb
module CampaignColorsHelper
end

app/helpers/campaign_tasks_helper.rb
module CampaignTasksHelper
end

app/helpers/campaign_templates_helper.rb
module CampaignTemplatesHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/crumb_templates_helper.rb
module CrumbTemplatesHelper
end

app/helpers/target_pages_helper.rb
module TargetPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/campaigns/_form.html.erb
<%= form_with(model: campaign, local: true) do |form| %>
  <% if campaign.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(campaign.errors.count, "error") %> prohibited this campaign from being saved:</h2>

      <ul>
      <% campaign.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :campaign_user_id %>
  </div>

  <div class="field">
    <%= form.label :compaign_name %>
    <%= form.text_field :compaign_name, id: :campaign_compaign_name %>
  </div>

  <%= form.fields_for :campaign_target_pages do |builder| %>

    <div class="field">
      <%= builder.label :campaign_target_page %>
      <%= builder.collection_select(:target_page_id, TargetPage.all, :id, :target_page_name, {prompt: true} )%>
    </div>

  <% end %>

  <%= form.fields_for :campaign_tasks do |builder| %>

    <div class="field">
      <%= builder.label :campaign_task %>
      <%= builder.collection_select(:task_id, Task.all, :id, :name, {prompt: true} )%>
    </div>

  <% end %>

  <%= form.fields_for :campaign_templates do |builder| %>

    <div class="field">
      <%= builder.label :crumb_campaign_template %>
      <%= builder.collection_select(:crumb_template_id, CrumbTemplate.all, :id, :name, {prompt: true} )%>
    </div>

  <% end %>

  <h3>Colors</h3>
  <%= form.fields_for :campaign_colors do |builder| %>

    <div class="field">
      <%= builder.label :color_type %>
      <%= builder.text_field :color_type, id: :campaign_color_color_type %>
    </div>
    <div class="field">
      <%= builder.label :hex_value %>
      <%= builder.color_field :hex_value, id: :campaign_color_hex_value %>
    </div>


  <% end %>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/campaigns/edit.html.erb
<h1>Editing Campaign</h1>

<%= render 'form', campaign: @campaign %>

<%= link_to 'Show', @campaign %> |
<%= link_to 'Back', campaigns_path %>

app/views/campaigns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Campaigns</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Compaign name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @campaigns.each do |campaign| %>
      <tr>
        <td><%= campaign.user %></td>
        <td><%= campaign.compaign_name %></td>
        <td><%= link_to 'Show', campaign %></td>
        <td><%= link_to 'Edit', edit_campaign_path(campaign) %></td>
        <td><%= link_to 'Destroy', campaign, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Campaign', new_campaign_path %>

app/views/campaigns/new.html.erb
<h1>New Campaign</h1>

<%= render 'form', campaign: @campaign %>

<%= link_to 'Back', campaigns_path %>

app/views/campaigns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @campaign.user %>
</p>

<p>
  <strong>Compaign name:</strong>
  <%= @campaign.compaign_name %>
</p>

<%= link_to 'Edit', edit_campaign_path(@campaign) %> |
<%= link_to 'Back', campaigns_path %>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :task_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :store_name %>
    <%= form.text_field :store_name, id: :user_store_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Store name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.store_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Store name:</strong>
  <%= @user.store_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>